
CREATE TABLE IF NOT EXISTS cresponses
(
    documentid  INTEGER UNSIGNED NOT NULL,
    cmpnyid     INTEGER UNSIGNED NOT NULL,
    detail      VARCHAR(999) DEFAULT NULL,
    message     VARCHAR(256) DEFAULT NULL,
    statusCode  INTEGER UNSIGNED NOT NULL DEFAULT 0,
    statusType  VARCHAR(16) NOT NULL DEFAULT 'Unknown',
    created     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX       documentndx(documentid)
)   ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = UTF8MB4;
