
CREATE TABLE IF NOT EXISTS settings
(
    slabel  VARCHAR(16) NOT NULL UNIQUE,
    svalue  VARCHAR(1024) DEFAULT NULL,
    sunit   VARCHAR(4) DEFAULT NULL,
    sdesc   VARCHAR(128) DEFAULT NULL,
    PRIMARY KEY(slabel)
)   ENGINE = InnoDB DEFAULT CHARSET = UTF8MB4;

