
CREATE TABLE IF NOT EXISTS profiles
(
    roleid      TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    rolename    VARCHAR(16) NOT NULL UNIQUE,
    roledesc    VARCHAR(128) DEFAULT NULL,
    PRIMARY KEY(roleid)
)   ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = UTF8MB4;

CREATE TABLE IF NOT EXISTS users
(
    usrid       INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    rolid       TINYINT UNSIGNED NOT NULL DEFAULT 4,
    email       VARCHAR(64) NOT NULL UNIQUE,
    username    VARCHAR(16) NOT NULL UNIQUE,
    fullname    VARCHAR(64) DEFAULT NULL,
    hashpswd    VARCHAR(99) NOT NULL,
    attempts    TINYINT UNSIGNED DEFAULT 0,
    lockedown   ENUM('N','Y') DEFAULT 'N',
    lastlogin   DATETIME DEFAULT NULL,
    registered  DATETIME NOT NULL,
    INDEX   userndx(username, lockedown),
    PRIMARY KEY(usrid),
    FOREIGN KEY(rolid) REFERENCES profiles(roleid) ON UPDATE CASCADE ON DELETE RESTRICT
)   ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = UTF8MB4;

CREATE TABLE IF NOT EXISTS passwords
(
    pswid       INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    userid      INTEGER UNSIGNED NOT NULL,
    pswdhash    VARCHAR(99) NOT NULL,
    PRIMARY KEY(pswid),
    INDEX pswdusr(userid),
    FOREIGN KEY(userid) REFERENCES users(usrid) ON UPDATE CASCADE ON DELETE RESTRICT
)   ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = UTF8MB4;
