spring.datasource.tomcat.min-idle=10
spring.datasource.tomcat.max-idle=100
spring.datasource.tomcat.max-wait=30000
spring.datasource.tomcat.max-active=100
spring.datasource.tomcat.initial-size=10
spring.datasource.tomcat.remove-abandoned=true
spring.datasource.tomcat.remove-abandoned-timeout=120
